apiVersion: v1
kind: ServiceAccount
metadata:
  name: clientid-operator-sa
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clientid-operator-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clientid-operator-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: clientid-operator-sa
  namespace: services
roleRef:
  kind: ClusterRole
  name: clientid-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clientid-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: clientid-operator
  template:
    metadata:
      labels:
        name: clientid-operator
    spec:
      serviceAccountName: clientid-operator-sa
      containers:
      - name: clientid-operator
        image: deggja/clientid-operator:latest
        args:
          - "--leader-elect=true"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
